// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkuCP03mpdpGI6mnP89wFnfRQk6umb7gw',
    appId: '1:479371676174:android:b678f3ebcba206367f4a5f',
    messagingSenderId: '479371676174',
    projectId: 'daniels-budget-app',
    databaseURL: 'https://daniels-budget-app-default-rtdb.firebaseio.com',
    storageBucket: 'daniels-budget-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCT43mZxI5MyqBKr4Mv0EniKVzBscpXI0',
    appId: '1:479371676174:ios:25f296c0a42650847f4a5f',
    messagingSenderId: '479371676174',
    projectId: 'daniels-budget-app',
    databaseURL: 'https://daniels-budget-app-default-rtdb.firebaseio.com',
    storageBucket: 'daniels-budget-app.appspot.com',
    iosClientId: '479371676174-7m15r8ogcctvgn1j1urcpa27e3fnlbbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
